version: 0.0
os: linux
files:
  - source: /
    destination: /opt/siso
permissions:
  - object: /opt/siso
    owner: ec2-user
    group: ec2-user
    mode: 755
    type: [directory]
hooks:
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ec2-user
