services:
  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    command: ["--character-set-server=utf8mb4","--collation-server=utf8mb4_unicode_ci","--max_connections=100"]
    environment:
      MARIADB_ROOT_PASSWORD: 1234
      MARIADB_DATABASE: sisoappdb
      MARIADB_USER: siso
      MARIADB_PASSWORD: 1234
    volumes:
      - dbdata:/var/lib/mysql
    # 외부 노출 불필요 → ports 생략(보안)
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -usiso -p1234 || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10

  app:
    build: .
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/sisoappdb?characterEncoding=utf8
      SPRING_DATASOURCE_USERNAME: siso
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MariaDBDialect

      # (최초 1회만 켜서 테이블 생성 → 생성되면 지우기)
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

      # ==== Kakao OAuth2 ====
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_ID: "96171e749ecdb7417189ae5b534534d0"
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_SECRET: ""
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_REDIRECT_URI: "http://localhost:8080/api/auth/kakao/callback"
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_AUTHORIZATION_GRANT_TYPE: "authorization_code"
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_AUTHENTICATION_METHOD: "client_secret_post"
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_SCOPE: "profile_nickname,account_email"
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KAKAO_AUTHORIZATION_URI: "https://kauth.kakao.com/oauth/authorize"
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KAKAO_TOKEN_URI: "https://kauth.kakao.com/oauth/token"
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KAKAO_USER_INFO_URI: "https://kapi.kakao.com/v2/user/me"
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KAKAO_USER_NAME_ATTRIBUTE: "id"
    ports:
      - "8080:8080"

volumes:
  dbdata:
