services:
  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --max_connections=200
    environment:
      TZ: ${TZ:-Asia/Seoul}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-1234}
      MARIADB_DATABASE: ${MARIADB_DATABASE:-sisoappdb}
      MARIADB_USER: ${MARIADB_USER:-siso}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-1234}
    volumes:
      - siso-backend_dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u${MARIADB_USER} -p${MARIADB_PASSWORD} || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: siso-app

    env_file: [".env"]

    ports:
      - "8080:8080"

    depends_on:
      mariadb:
        condition: service_healthy

    volumes:
      # ✅ secrets 바인드로 교체
      - /opt/siso/secrets/firebase-adminsdk.json:/run/secrets/firebase-adminsdk.json:ro

    environment:
      TZ: ${TZ:-Asia/Seoul}

      SPRING_DATASOURCE_URL: jdbc:mysql://mariadb:3306/${MARIADB_DATABASE:-sisoappdb}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&connectTimeout=10000&socketTimeout=20000
      SPRING_DATASOURCE_USERNAME: ${MARIADB_USER:-siso}
      SPRING_DATASOURCE_PASSWORD: ${MARIADB_PASSWORD:-1234}

      SPRING_JPA_HIBERNATE_DDL_AUTO: create
      SPRING_SQL_INIT_MODE: never

      AGORA_APP_ID: ${AGORA_APP_ID:-a914eda873c04f09a72ee7bd3e522300}
      AGORA_APP_CERTIFICATE: ${AGORA_APP_CERTIFICATE:-8fe69592f65b4bc6ae550a5299eb7c36}

      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-prod}
      SPRING_CONFIG_IMPORT: ${SPRING_CONFIG_IMPORT:-optional:application-secret.yml}

      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_SECRET: ${KAKAO_CLIENT_SECRET}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_REDIRECT_URI: ${KAKAO_REDIRECT_URI}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_AUTHORIZATION_GRANT_TYPE: authorization_code
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_AUTHENTICATION_METHOD: client_secret_post
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_SCOPE: profile_nickname,account_email
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KAKAO_AUTHORIZATION_URI: https://kauth.kakao.com/oauth/authorize
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KAKAO_TOKEN_URI: https://kauth.kakao.com/oauth/token
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KAKAO_USER_INFO_URI: https://kapi.kakao.com/v2/user/me
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KAKAO_USER_NAME_ATTRIBUTE: id
      JWT_SECRET: ${JWT_SECRET}

    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:8080/actuator/health | grep -q '\"status\":\"UP\"'"]
      interval: 5s
      timeout: 2s
      retries: 30
      start_period: 20s
    stop_grace_period: 20s
    restart: unless-stopped

volumes:
  siso-backend_dbdata: {}
