services:
  app:
    build: .
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/sisoappdb?characterEncoding=utf8
      SPRING_DATASOURCE_USERNAME: siso
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MariaDBDialect
      # 필요 시 테이블 자동생성 1회만
      # SPRING_JPA_HIBERNATE_DDL_AUTO: update

      # (선택) 프로파일 사용 시
      # SPRING_PROFILES_ACTIVE: prod

      # ==== Kakao OAuth2 (필수) ====
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_ID: "96171e749ecdb7417189ae5b534534d0"
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_SECRET: ""   # 쓰면 값, 보통 공란 가능
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_REDIRECT_URI: "http://localhost:8080/api/auth/kakao/callback"  # 로컬 테스트용
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_AUTHORIZATION_GRANT_TYPE: "authorization_code"
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_AUTHENTICATION_METHOD: "client_secret_post"
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_SCOPE: "profile_nickname,account_email"

      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KAKAO_AUTHORIZATION_URI: "https://kauth.kakao.com/oauth/authorize"
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KAKAO_TOKEN_URI: "https://kauth.kakao.com/oauth/token"
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KAKAO_USER_INFO_URI: "https://kapi.kakao.com/v2/user/me"
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KAKAO_USER_NAME_ATTRIBUTE: "id"
    ports:
      - "8080:8080"