spring:
  config:
    import: application-secret.yml

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  image:
    use_s3: ${IMAGE_USE_S3:true}         # 운영:true, 로컬은 필요시 false
    max-images-per-user: 5

  # 배포용 AWS S3 설정 (로컬에서는 application-local.yml의 설정 사용)
cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: siso-deploy

server:
  address: 0.0.0.0
  port: 8080

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never

      #자동배포 테스트 확인