spring:
  config:
    activate:
      on-profile: dev

  datasource:
    # 로컬 MySQL 쓰면 127.0.0.1, EC2 DB를 개발중에 공유로 쓰고 싶으면 13.124.11.3로.
    url: ${DB_URL:jdbc:mysql://127.0.0.1:3306/sisoappdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&connectTimeout=10000&socketTimeout=20000&characterEncoding=utf8}
    username: ${DB_USERNAME:siso}
    password: ${DB_PASSWORD:1234}
    hikari:
      maximum-pool-size: 5
      connection-timeout: 15000
      validation-timeout: 5000
      connection-test-query: SELECT 1

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID:96171e749ecdb7417189ae5b534534d0}
            # 로컬에서 콜백 받을 때는 보통 localhost로 둡니다.
            redirect-uri: ${KAKAO_REDIRECT_URI:http://localhost:8080/api/auth/kakao/callback}

kakao:
  client-id: ${KAKAO_CLIENT_ID:96171e749ecdb7417189ae5b534534d0}
  redirect-uri: ${KAKAO_REDIRECT_URI:http://localhost:8080/api/auth/kakao/callback}

app:
  voice-sample:
    upload-dir: ${VOICE_UPLOAD_DIR:./uploads/voice-samples}
    base-url: ${VOICE_BASE_URL:http://localhost:8080/static/voice-samples}
  image:
    upload-dir: ${IMAGE_UPLOAD_DIR:./uploads/images}
    base-url: ${IMAGE_BASE_URL:http://localhost:8080/static/images}