spring:
  config:
    import: application-local.yml

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

server:
  address: 0.0.0.0
  port: 8080

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never

image:
  profile:
    upload_path: "uploads/images/profiles"
  use_s3: ${IMAGE_USE_S3:true}
  view_url: "/api/v1/images/view/" # 이미지를 보는용, s3는 버킷 저장소 url

cloud:
  aws:
    s3:
      bucket: siso-deploy
