spring:
  profiles:
    active: local
# dev에서는 'profiles: active: local' 지우기

  jpa:
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
    security:
      oauth2:
        client:
          provider:
            kakao:
              user-name-attribute: kakao_account
              authorization-uri: https://kauth.kakao.com/oauth/authorize
              token-uri: https://kauth.kakao.com/oauth/token
              user-info-uri: https://kapi.kakao.com/v2/user/me

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never