spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://127.0.0.1:13306/sisoappdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&connectTimeout=10000&socketTimeout=20000}
    username: ${DB_USERNAME:siso}
    password: ${DB_PASSWORD:1234}
    # driver-class-name: com.mysql.cj.jdbc.Driver   # (원하면 명시)
    hikari:
      maximum-pool-size: 5
      connection-timeout: 15000
      validation-timeout: 5000
      connection-test-query: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect   # 팀 표준이면 명시 추천
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update     # 개발용

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
# ===== 음성 샘플 관련 설정 =====$
app:
  voice-sample:
    upload-dir: uploads/voice-samples        # 파일 저장 디렉토리
    base-url: http://localhost:8080          # 파일 접근 기본 URL
    max-file-size: 52428800                  # 50MB in bytes
    supported-formats:                           # 지원 파일 형식
      - mp3
      - wav
      - m4a
      - aac
      - ogg
      - webm
      - flac
    max-duration: 20                         # 최대 녹음 시간 (초 단위)
    max-voice-samples-per-user: 1            # 사용자당 최대 음성 샘플 개수

  # ===== 이미지 관련 설정 =====
  image:
    upload-dir: uploads/images               # 파일 저장 디렉토리
    base-url: http://localhost:8080          # 파일 접근 기본 URL
    max-file-size: 10485760                  # 10MB in bytes
    supported-formats:                       # 지원 파일 형식
      - jpg
      - jpeg
      - png
      - gif
      - webp
    max-images-per-user: 5                   # 사용자당 최대 이미지 개수

    springdoc:
      api-docs:
        enabled: true
      swagger-ui:
        path: /swagger-ui
        operationsSorter: method   # (선택) 메서드명 정렬
        tagsSorter: alpha          # (선택) 태그 알파벳 정렬